---
title: "Russia manipulation Notebook"
output: html_notebook
---


```{r setup}
library(readxl)
library(interplot)
library(lme4)
library(tidyverse)
rus.data <- read_xlsx("russia full ts data.xlsx")

rus.data <- rus.data %>% mutate(spikes.ur.pct = spikes.precincts.ur / n.precincts)
```




```{r}
model.ur.voteshare <- lmer(ur.voteshare ~ pistar.ur +  comp.scale03_18 + pct.russian.extrap + he.graduates.by1000pop + govemploy.by.pop +
                             urban.pct + pensioners.per.1000 + poverty.pct + presidential +
                             pistar.ur*comp.scale03_18 +
                             (1 | regionid), data=rus.data)
summary(model.ur.voteshare)
interplot(model.ur.voteshare, var1="pistar.ur", var2="comp.scale03_18")
```


```{r}
model.ur.tc <- lmer(coefficient.ur ~ comp.scale03_18  + he.graduates.by1000pop +                                                    govemploy.by.pop +
                             urban.pct + pensioners.per.1000 + poverty.pct + presidential +
                             urgov.pct.updated*comp.scale03_18 +
                             (1 | regionid), data=rus.data)
summary(model.ur.tc)
interplot(model.ur.tc, var2="urgov.pct.updated", var1="comp.scale03_18")
```



```{r}
model.ur.ps <- lmer(pistar.ur ~ comp.scale03_18 + absentee.coef + he.graduates.by1000pop +                                                    govemploy.by.pop +
                             urban.pct + pensioners.per.1000 + poverty.pct + presidential +
                             urgov.pct.updated*comp.scale03_18 +
                             (1 | regionid), data=rus.data)
summary(model.ur.ps)
interplot(model.ur.ps, var1="urgov.pct.updated", var2="comp.scale03_18")
```


```{r}
model.ur.d <- lmer(delta.ur ~ comp.scale03_18 +  he.graduates.by1000pop +                                                    govemploy.by.pop +
                             urban.pct + pensioners.per.1000 + poverty.pct + presidential +
                             urgov.pct.updated*comp.scale03_18 +
                             (1 | regionid), data=rus.data)
summary(model.ur.d)
interplot(model.ur.d, var1="urgov.pct.updated", var2="comp.scale03_18")
```


```{r}
model.ur.f <- glmer(anyfraud ~ comp.scale03_18 + absentee.coef + he.graduates.by1000pop +                                                    govemploy.by.pop +
                             urban.pct + pensioners.per.1000 + poverty.pct + presidential +
                             urgov.pct.updated*comp.scale03_18 + 
                             (1 | regionid), data=rus.data, family=binomial(link="logit"))
summary(model.ur.f)
interplot(model.ur.f, var2="urgov.pct.updated", var1="comp.scale03_18")
```


```{r}
model.ur.spikes <- lmer(spikes.ur.pct ~ comp.scale03_18  + he.graduates.by1000pop +                                                    govemploy.by.pop +
                             urban.pct + pensioners.per.1000 + poverty.pct + presidential +
                             urgov.pct.updated*comp.scale03_18 + 
                             (1 | regionid), data=rus.data)
summary(model.ur.spikes)
interplot(model.ur.spikes, var2="urgov.pct.updated", var1="comp.scale03_18")
```
